def app = [appName: 'example-app',   appPort: '8080']

pipeline {


    /* Environment variables related to docker hub */
    environment {
        registry = "nisumpk"
        registryCredential = 'docker-hub-credentials'
        dockerHost = 'localhost'
    }

    agent any

    tools {
        maven 'apache-maven'
    }

    stages {

        stage('Clone Application') {
            /* Git checkout using declarative method 'scm' */
            //steps {
            //    checkout scm
            //}
            /* Git checkout */
            steps {
                checkout([$class: 'GitSCM',
                branches: [[name: '*/master']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']],
                submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: '51bba3a5-b569-4119-83e2-3371795d5b23', url: 'https://github.com/fqadeer-nisum-com/the-example-app.java.git']]
                //userRemoteConfigs: [[credentialsId: '16e9c02e-8b5a-41de-b05e-5c0ac770dc97', url: 'https://github.com/nisum-inc/POC_Discovery_Server.git']]
                ])
            }
        }

        stage('Build Application') {
            steps {
                sh "cd ${WORKSPACE} && ./gradlew build"
            }
        }

        stage('Building Images') {
            steps {
                script {
                    /* Copying jar file to relavant directory */
                    sh script: "cp  ${WORKSPACE}/application.properties  ${WORKSPACE}/build/resources/main/"
                    sh script: "cp -r ${WORKSPACE}/build" ${WORKSPACE}/build.gradle ${WORKSPACE}/gradle ${WORKSPACE}/gradle.properties ${WORKSPACE}/gradlew ${WORKSPACE}/src ${WORKSPACE}/install/deploy/docker/" + app.appName.replaceAll("-", "_") + "/"

                    /* Building docker image */
                    docker.build(registry + "/" + app.appName.replaceAll("-", "_"), "-f ${WORKSPACE}/install/deploy/docker/" + app.appName.replaceAll("-", "_") + "/Dockerfile ${WORKSPACE}/install/deploy/docker")
                }
            }
        }


    }
}